export default ACTIONS = {
  SET_CUR_SCREENT: 'SET_CUR_SCREENT',
  SET_USER_INFO: 'SET_USER_INFO',
  SET_LIST_CLASS: 'SET_LIST_CLASS',
  SET_CUR_ROOM: 'SET_CUR_ROOM',
  LOGOUT: 'LOGOUT',
  SET_CUR_CLASS: 'SET_CUR_CLASS',
  GO_BACK: 'GO_BACK',
};
